### ISSUE TITLE
Auto-updater is not working

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/digiwords_ynh#14]
cf. past runs: https://github.com/YunoHost-Apps/digiwords_ynh/actions/workflows/updater.yml
I have disabled the workflow.

**Comment by pagiraud** [comment]
Thanks. I never managed to make it work. I have to dig and take some time to understand how to make workflows.

**Comment by ericgaspar** [comment]
fix by removing the autoupdater 😬
